menubar:
  columms: 2
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 博客 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: notebook
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 笔记
      url: /notebooks/
    # - id: explore
    #   theme: '#FA6400'
    #   icon: solar:planet-bold-duotone
    #   title: 探索
    #   url: /explore/
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/
comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v3/dist/waline.js
    css: https://unpkg.com/@waline/client@v3/dist/waline.css
    serverURL: https://comment.api.ed-builder.top # waline 地址
    commentCount: true
    pageview: true
    emoji:
      - https://unpkg.com/@waline/emojis@1.1.0/bilibili

katex:
  enable: true # hexo-renderer-markdown-it-plus 默认开启 katex，此选项仅用于引入样式
  inject: |
      <link rel="stylesheet" href="https://jsd.nmmsl.top/npm/katex@0.16/dist/katex.min.css">
style:
  prefers_theme: light
footer:
  social:
    Luogu:
      icon: '<img src="https://fecdn.luogu.com.cn/columba/static.325908fec383795b.logo-single-color.svg"/>'
      url: https://www.luogu.com.cn/user/1023494
    Comments:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/942ebbf1a4b91.svg"/>'
      url: https://comment.api.ed-builder.top
  content: | 
    本站由 [ED_Builder](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。
    本站所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    LoveStarForever
inject:
  head:
    - <link rel="stylesheet" href="https://jsd.nmmsl.top/npm/katex@0.16/dist/katex.min.css">